import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FakeSpot",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
  heading,
}: {
  children: React.ReactNode;
  heading: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {heading}
        {children}
      </body>
    </html>
  );
}
