import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext"; 
import { Toaster } from "react-hot-toast";
import React, { createContext, useContext } from "react";
import MyApolloProvider from "@/context/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CrimeWatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ... rest of the code

  return (
    <html lang="en">
      <body className="h-screen max-w-screen-2xl bg-background font-rale text-md mx-auto">
        <MyApolloProvider>
          <AuthContext>
            <Toaster
              position="top-center"
              reverseOrder={false}
              toastOptions={{ duration: 5000 }}
            />
            {children}
          </AuthContext>
        </MyApolloProvider>
      </body>
    </html>
  );
}
